name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: installations
      run: sudo apt install libsodium-dev && sudo apt install criterion

    - name: test
      run: make test
